name: PR build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
permissions: {}
jobs:
  test-codepropertygraph:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      with:
        lfs: true
        persist-credentials: false
    - name: Clone submodules
      run: git submodule update --init --recursive
    - name: Set up JDK
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287  # v5.3.0
      with:
        distribution: 'temurin'
        java-version: '25'
    - uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821  # v1
    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5.0.5
      with:
        path: |
          ~/.sbt
          ~/.coursier
        key: ${{ runner.os }}-sbt-${{ hashfiles('**/build.sbt') }}
    - name: Compile and run tests
      run: sbt clean stage +test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
