name: master & release build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:    # allow to manually trigger this workflow
jobs:
  test-codepropertygraph:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        fetch-depth: 0
    - name: Clone submodules
      run: git submodule update --init --recursive
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Compile and run tests
      run: sbt stage +test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    concurrency: release
    needs: [test-codepropertygraph]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - name: Clone submodules
        run: git submodule update --init --recursive
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: sbt stage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: sbt publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
