name: master & release build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:    # allow to manually trigger this workflow
jobs:
  release:
    concurrency: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - name: Clone submodules
        run: git submodule update --init --recursive
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Compile and run tests
        run: sbt clean stage +test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: sbt publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
